# Generated by Django 5.1.7 on 2026-04-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='week_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
